### ISSUE TITLE
respect https

### ISSUE THREAD

**Issue by ryanramage** [garden20/garden-market#3]
https://github.com/garden20/garden-market/blob/master/lib/utils.js#L43-L46

seems we have hardcoded http in a few places.

**Comment by mandric** [comment]
We recently switched to SSL for our markets and are experiencing this bug.  The market responds with a `db_src` ([code](https://github.com/garden20/garden-market/blob/master/lib/shows.js#L86)) of http: yet the market is being served off https.  I also don't really see anything in the request object from couchdb that lets us know this is an SSL request, or gives us a hint on how to construct the protocol of the URL.  Here's an example request object. Let me know if you have any ideas.  The only thing I can think of is to pass in a header from the SSL proxy (nginx) to help set the right protocol on `db_src`.

```
{
  "info": {
    "db_name": "market",
    "doc_count": 7,
    "doc_del_count": 0,
    "update_seq": 55,
    "purge_seq": 1,
    "compact_running": false,
    "disk_size": 370597997,
    "data_size": 50578535,
    "instance_start_time": "1417463211173996",
    "disk_format_version": 6,
    "committed_update_seq": 55
  },
  "id": "medic",
  "uuid": "0a87476e80957abceafaa5d6c286a232",
  "method": "GET",
  "requested_path": [
    "details",
    "medic",
    "json"
  ],
  "path": [
    "market",
    "_design",
    "market",
    "_show",
    "kanso_details",
    "medic"
  ],
  "raw_path": "/market/_design/market/_show/kanso_details/medic?name=medic",
  "query": {
    "name": "medic"
  },
  "headers": {
    "Accept": "*/*",
    "Connection": "close",
    "Host": "staging.dev.medicmobile.org",
    "User-Agent": "curl/7.37.1",
    "x-couchdb-requested-path": "/market/_design/market/_rewrite/details/medic/json",
    "x-couchdb-vhost-path": "/details/medic/json",
    "X-Forwarded-For": "108.428.16.140",
    "X-Real-Ip": "108.428.16.140"
  },
  "body": "undefined",
  "peer": "108.428.16.140",
  "form": {},
  "cookie": {},
  "userCtx": {
    "db": "market",
    "name": null,
    "roles": []
  },
  "secObj": {
    "admins": {
      "names": [],
      "roles": []
    },
    "members": {
      "names": [],
      "roles": []
    }
  }
}
```

**Comment by mandric** [comment]
So then `garden-core <ssl url>` fails because it tries to use the db_src value which contains http instead of https.  The http (non-ssl) address returns 301 and the replication and memory fallback both fail on the 301.
